import { DynamicPageEntityProps } from '@piar/domain-models';
import { baseEntityFieldsConfig } from './base-entity.config';
import { EntityFieldsConfig, FieldType } from '../common/types';

const dynamicPageStatusOptions = [
  { value: 'draft', label: 'options.dynamicPage.status.draft.label' },
  { value: 'published', label: 'options.dynamicPage.status.published.label' },
  { value: 'archived', label: 'options.dynamicPage.status.archived.label' },
];

/**
 * Dynamic page entity fields configuration
 */
export const dynamicPageEntityFieldsConfig: EntityFieldsConfig<DynamicPageEntityProps> = {
  entityName: 'DynamicPageEntity',
  fields: [
    ...baseEntityFieldsConfig.fields,
    {
      key: 'pageCode',
      type: FieldType.String,
      label: 'fields.dynamicPage.pageCode.label',
      description: 'fields.dynamicPage.pageCode.description',
      required: true,
      editable: true,
      visible: true,
      validation: [
        { minLength: 3, message: 'validation.dynamicPage.pageCode.minLength' },
        { maxLength: 60, message: 'validation.dynamicPage.pageCode.maxLength' },
        {
          pattern: /^[A-Z0-9_-]+$/,
          message: 'validation.dynamicPage.pageCode.pattern',
        },
      ],
      ui: {
        component: 'input',
        placeholder: 'fields.dynamicPage.pageCode.placeholder',
        helpText: 'fields.dynamicPage.pageCode.helpText',
      },
      permissions: { view: ['admin', 'user'], edit: ['admin'] },
    },
    {
      key: 'slug',
      type: FieldType.String,
      label: 'fields.dynamicPage.slug.label',
      description: 'fields.dynamicPage.slug.description',
      required: true,
      editable: true,
      visible: true,
      validation: [
        { minLength: 2, message: 'validation.dynamicPage.slug.minLength' },
        { maxLength: 120, message: 'validation.dynamicPage.slug.maxLength' },
        {
          pattern: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
          message: 'validation.dynamicPage.slug.pattern',
        },
      ],
      ui: {
        component: 'input',
        placeholder: 'fields.dynamicPage.slug.placeholder',
        helpText: 'fields.dynamicPage.slug.helpText',
      },
      permissions: { view: ['admin', 'user'], edit: ['admin'] },
    },
    {
      key: 'status',
      type: FieldType.Select,
      label: 'fields.dynamicPage.status.label',
      description: 'fields.dynamicPage.status.description',
      required: false,
      editable: true,
      visible: true,
      defaultValue: 'draft',
      options: dynamicPageStatusOptions,
      ui: { component: 'select' },
      permissions: { view: ['admin', 'user'], edit: ['admin'] },
    },
    {
      key: 'hero',
      type: FieldType.JSON,
      label: 'fields.dynamicPage.hero.label',
      description: 'fields.dynamicPage.hero.description',
      required: true,
      editable: true,
      visible: true,
      defaultValue: {
        title: [{ language: 'en', value: '' }],
      },
      ui: { component: 'json-editor', rows: 8 },
      permissions: { view: ['admin', 'user'], edit: ['admin', 'user'] },
    },
    {
      key: 'sections',
      type: FieldType.JSON,
      label: 'fields.dynamicPage.sections.label',
      description: 'fields.dynamicPage.sections.description',
      required: false,
      editable: true,
      visible: true,
      defaultValue: [],
      ui: { component: 'json-editor', rows: 8 },
      permissions: { view: ['admin', 'user'], edit: ['admin', 'user'] },
    },
    {
      key: 'seo',
      type: FieldType.JSON,
      label: 'fields.dynamicPage.seo.label',
      description: 'fields.dynamicPage.seo.description',
      required: false,
      editable: true,
      visible: true,
      defaultValue: {},
      ui: { component: 'json-editor', rows: 6 },
      permissions: { view: ['admin', 'user'], edit: ['admin', 'user'] },
    },
    {
      key: 'isActive',
      type: FieldType.Boolean,
      label: 'fields.dynamicPage.isActive.label',
      description: 'fields.dynamicPage.isActive.description',
      required: false,
      editable: true,
      visible: true,
      defaultValue: true,
      ui: { component: 'switch' },
      permissions: { view: ['admin', 'user'], edit: ['admin'] },
    },
    {
      key: 'webPriority',
      type: FieldType.Number,
      label: 'fields.dynamicPage.webPriority.label',
      description: 'fields.dynamicPage.webPriority.description',
      required: false,
      editable: true,
      visible: true,
      defaultValue: 0,
      validation: [
        { min: 0, message: 'validation.dynamicPage.webPriority.min' },
        { max: 9999, message: 'validation.dynamicPage.webPriority.max' },
      ],
      ui: {
        component: 'number',
        placeholder: 'fields.dynamicPage.webPriority.placeholder',
        helpText: 'fields.dynamicPage.webPriority.helpText',
      },
      permissions: { view: ['admin', 'user'], edit: ['admin'] },
    },
    {
      key: 'showOnPublicWeb',
      type: FieldType.Boolean,
      label: 'fields.dynamicPage.showOnPublicWeb.label',
      description: 'fields.dynamicPage.showOnPublicWeb.description',
      required: false,
      editable: true,
      visible: true,
      defaultValue: false,
      ui: { component: 'switch' },
      permissions: { view: ['admin', 'user'], edit: ['admin'] },
    },
    {
      key: 'metadata',
      type: FieldType.JSON,
      label: 'fields.dynamicPage.metadata.label',
      description: 'fields.dynamicPage.metadata.description',
      required: false,
      editable: true,
      visible: true,
      ui: { component: 'json-editor' },
      permissions: { view: ['admin'], edit: ['admin'] },
    },
  ],
  groups: [
    {
      id: 'basic',
      label: 'Dynamic Page',
      description: 'Main dynamic page fields',
      fields: ['pageCode', 'slug', 'status'],
      collapsible: false,
      order: 1,
    },
    {
      id: 'hero',
      label: 'Hero',
      description: 'Hero block configuration',
      fields: ['hero'],
      collapsible: true,
      defaultCollapsed: false,
      order: 2,
    },
    {
      id: 'content',
      label: 'Content',
      description: 'Content sections configuration',
      fields: ['sections'],
      collapsible: true,
      defaultCollapsed: false,
      order: 3,
    },
    {
      id: 'seo',
      label: 'SEO',
      description: 'SEO configuration',
      fields: ['seo'],
      collapsible: true,
      defaultCollapsed: true,
      order: 4,
    },
    {
      id: 'status',
      label: 'Publication',
      description: 'Publication status and visibility',
      fields: ['isActive', 'webPriority', 'showOnPublicWeb'],
      collapsible: true,
      defaultCollapsed: false,
      order: 5,
    },
    {
      id: 'metadata',
      label: 'Metadata',
      description: 'Extra metadata',
      fields: ['metadata'],
      collapsible: true,
      defaultCollapsed: true,
      order: 6,
    },
    ...(baseEntityFieldsConfig.groups || []),
  ],
};

export const dynamicPageSpecificFields = dynamicPageEntityFieldsConfig.fields.filter(
  (field) => !['id', 'createdAt', 'updatedAt'].includes(field.key as string),
);
